export enum ErrorCode {
  NETWORK_ERROR = 'NETWORK_ERROR',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  DATA_NOT_FOUND = 'DATA_NOT_FOUND',
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  EXPIRED_TOKEN = 'EXPIRED_TOKEN',
  ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND',
  WRONG_CREDENTIALS = 'WRONG_CREDENTIALS',
}


export interface IApiError {
  status: number
  code: ErrorCode
}
