const NODE_ENV = process.env.NODE_ENV || 'development'
const API_ENDPOINT = process.env.NEXT_PUBLIC_API_URL || 'your_url_here'
const GOOGLE_ANALYTICS_ID = process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID
const SONARCLOUD_TOKEN = process.env.SONARCLOUD_TOKEN

export { API_ENDPOINT, NODE_ENV, GOOGLE_ANALYTICS_ID, SONARCLOUD_TOKEN }
